### ISSUE TITLE
Warlock doesn't throw enderpearls, he just pushes them up

### ISSUE THREAD

**Issue by xBiscuit** [mcmonkey4eva/Sentinel#112]
Video: http://sendvid.com/fwe1xww1
The Warlock should be throwing an enderpearl that pushes them up when hit.
But instead, he just pushes them up with a non-existant enderpearl
I think you missed it last time I sent you the video ;p
Thanks,
- xBiscuit

**Comment by xBiscuit** [comment]
Also, since I can't seem to find a way to contact you, how can you equip a citizen with tipped arrows but still holding a bow? I want a citizen to shoot spectral arrows.

**Comment by mcmonkey4eva** [comment]
Yeah that's intentional.
I didn't feel like trying to manage and clean up the mess of spawning ender pearls there when there was no actual usage of them needed.

You can contact me via http://one.denizenscript.com/ircchat_denizen <-- my usual IRC channel, full of Citizens/related chatter.
And use `/npc inventory` to give it items to uses separate from its held item.

**Comment by xBiscuit** [comment]
I think it adds a lot to the effect when throwing the held item. Any enderpearl thrown in the general direction will do it, i don't care if it doesn't directly hit. If its too messy then its fine, thanks anyways!

**Comment by mcmonkey4eva** [comment]
Eh... Denizen can add such an effect far easier than Sentinel can, thanks to it already having relevant internals that interact with lower-level minecraft code.
So, if you or anyone reading this really want such an effect, I would recommend the first attempt be made via attaching a script in Denizen or somethin https://wiki.citizensnpcs.co/Denizen - can give help for that in the IRC link above if there's trouble completing that.
