### ISSUE TITLE
Guard distance

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkey4eva/Sentinel#133]
Its me again :)

I want some NPCs to guard me. But they dont find the way through doors etc. So the question is, if I can change the distance of the guardian to follow me. With a short distance he would find the way on corners or doors. If there isn´t this option, can u add it?

Greetings, Firemonkey

**Comment by mcmonkey4eva** [comment]
Definitely could add an option for that!

**Comment by Firemonkey08** [comment]
Yeah. You are my man 👍

**Comment by mcmonkey4eva** [comment]
Sorry for the weirdly long (one and a half years!) delay on this! I've been distracted and forgot I had left some not too difficult to add issues open.

I've added new config options for this (3 of them, under 'guard follow distance').
The 3 of them are separate due to the feature added following issue #258 (see there for some relevant notes)

This fix is included in Sentinel build DEV-183+ http://ci.citizensnpcs.co/job/Sentinel/
