### ISSUE TITLE
Sentinels don't know what to do in water

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#201]
Hello,

There are some severe issues with sentinels movement in water. In general, if they go in waters, they won't be able to come out or won't know what to do, thus making it extremely easy to deafeat them.

Small demonstration (but there are many other issues similar to the one shown here) :
https://streamable.com/y4i8l

Thank you for looking into this.

**Comment by mcmonkey4eva** [comment]
Citizens navigation issue.

**Comment by Ferocimo** [comment]
We thought it was that at first, but then we performered a test on a NPC : we put its waypoints path in water, and watched it normally reach any waypoints that we put in water. The NPC, if left alone, doesn't seem to have any major issue with movement in water (just a bit irrealistic since it makes some weird moves but that's all). It's only when it has to attack a player that is in water (and the NPC is in water too) that it completely stops moving and just stares at the player, waiting. It seems to have troubles knowing how to reach the player, even though it doesn't have troubles to reach a waypoint that would have been placed at the exact same position the player is.

**Comment by 123123b** [comment]
Sometimes I have this issue too. When the Sentinels don't see a target, they simply swim like a normal person to their waypoints. When they see an enemy, they get stuck and have difficulty navigating the water. They stay still, jerk off, start going the wrong way, etc.

**Comment by Blamo27** [comment]
@123123b new video link : https://streamable.com/y4i8l

**Comment by 123123b** [comment]
> @123123b new video link : https://streamable.com/y4i8l
Yep, almost exactly like that. Ranged or not. Other times they just malfunction in general

**Comment by mcmonkey4eva** [comment]
It's just a standard entity-follow in the Citizens API... I don't see anything in Sentinel that would mess with that much at all...

**Comment by Blamo27** [comment]
@mcmonkey4eva any news about this bug ? :/
=> Maybe you can patch that or inform Citizens contributors ?

**Comment by Blamo27** [comment]
@mcmonkey4eva 
Fullwall replied that "Latest build includes a fix for the Citizens pathfinder".
I'm gonna check the fix tonight !

**Comment by mcmonkey4eva** [comment]
I saw. I'm speaking to him on Discord voice chat right now about that. I've relayed that you'll be checking it soon to him, since apparently we're all just communicating in side channels and relays now :D

**Comment by Blamo27** [comment]
Nope, I am just sulking fullwall !

**Comment by Blamo27** [comment]
It's working with the last Citizens build, see also Ferocimo's answer :
https://github.com/CitizensDev/Citizens2/issues/1298#issuecomment-374047829
