### ISSUE TITLE
NPCs does not give damage

### ISSUE THREAD

**Issue by techboy04** [mcmonkey4eva/Sentinel#213]
When I make the NPCs, they attack but seems like the player is getting NO damage. On the stats of the NPC it says "Attack Given: .NaN" so I think that might mean an error. Hopefully I can get help as soon as possible. I tried updating but I am not sure that its the problem since both Citizens and Sentinel are updated when I have this issue.

**Comment by mcmonkey4eva** [comment]
Did you follow the readme instructions?
```
:
NPC's won't do melee damage? In your config.yml file, toggle the setting that says "workaround damage" to true, and restart your server!
NPC's won't do ranged damaged, or protection plugins causing problems? In your config.yml file, toggle the setting that says "enforce damage" to true, and restart your server!

**Comment by techboy04** [comment]
The plugin does not have neither of the workaround damage nor the enforce damage setting.

**Comment by techboy04** [comment]
![2017-11-04_19 36 36](https://user-images.githubusercontent.com/26682382/32411438-bda92bb2-c197-11e7-985c-ea92af631f47.png)

**Comment by Formula350** [comment]
Have you tried making sure that if you're in a WorldGuard region that `pvp allow` flag is set? 

Also, have you tried re-making the NPC/Sentinel fresh? Or making another one just to see if it's something wrong with that specific Sentinel?

Lastly, have you tried editing the Citizens `save.yml`, finding that specific NPC's data, changing the Sentinel Damage entry to an actual value instead of `.NaN`, saving the changes and using `/citizen load`?
(Alternatively, stopping the server first, making the changes, saving them and then starting the server, which would be the ideal/suggested way to do that.)

Uploading your saves.yml to https://gist.github.com and posting the link here might help, too.
