### ISSUE TITLE
An NPC Never Forgets (who its targeting...)

### ISSUE THREAD

**Issue by Formula350** [mcmonkey4eva/Sentinel#218]
Sentinel v1.4.5 build 157
Citizens 2.0.22 build 1494
Spigot 1.11.2

Having some issues with certain NPCs having unrelenting hatred towards certain players, where no matter what others, or even myself try to do, the NPC will not attack ANYone else until the 'hated player' leaves the area...

This issue persists through the NPC's death, that player's death, that player reconnecting, and.... curious of all things even through server restarts. 

I'll set the stage:
 -Player **A** enters the arena of an NPC, starts attacking it, the NPC starts attacking back and following them.
 -Player ***B*** now enters that arena, NPC makes a bee-line to Player ***B*** and starts attacking it, unprovoked.
 -Player **A** attacks the NPC, but the NPC doesn't care, continues to target and attack Player ***B***.
 -I run `/sentinel realistic` thinking since something odd is going on that might help, but nothing happens.
 -I run `/sentinel forgive`, nothing happens.
 -I run `/sentinel  targettime 10` in hopes it'll allow it to forget who its targeting... still nothing happens. 
 -I double check the target and it's set to `PLAYER`, and no one specific. (Owner is set as `Server` for the record)

The only time it ever attacks Player **A** is when Player ***B*** leaves the area (out of target range).

I don't know if I'm just an idiot and missing something, or if it's somehow a cause of importing Sentry into Sentinel *(since I had plenty of issues, such as with the Dropped item not converting, and all of them having 100% armor)*, or if this is a legitimate bug :\

Anyways here are the configs...
**Sentinel:**
https://gist.github.com/Formula350/e9bb3d9beba8c318613ebabe9a690f92

**Citizens:**
https://gist.github.com/Formula350/66d3da3c9679c1cb35604b580b688142

**That NPC:**
https://gist.github.com/Formula350/9be667ea7c7914dd052d8a584da1811e

**Comment by Blamo27** [comment]
@Formula350 next time use pastebin :')

**Comment by Formula350** [comment]
You're right, in hindsight it was poor form for me to paste using `code`, so I've edited it to utilize GitHub's own Pastebin: Gist.GitHub.com

**Comment by Midnight9746** [comment]
Hi Formy!!

If you still have that problem, try removing the trait from the npc, restart, and then reconfigure him. I would say removing him, but I know you got quests linked to him. Unless you're prepared to update npcs id's.

It might have some sort of data stored that isn't getting updated properly that loads with old targets, thus probably why it hates a player through the restart and even after forgiving them.

**Comment by mcmonkey4eva** [comment]
Is this still an issue?

Sentinel NPC's will prioritize targets based on multiple factors, and it's possible there's just some inconsistencies between what you intend to happen and what priorities the NPC has.

When an NPC has multiple valid targets, priority logic is:
Find targets closest to guard point. When the NPC is guarding a player, that is the guard point. Otherwise, when a point is set through `/npc path`, that point is the guard point. Otherwise, the guard point is the NPC's own location.
Generally, closer to the guard point is higher priority target.
As an exception, in a choice between a target that's closer but is out of line-of-sight, and a target that is farther but in line-of-sight, the visible target is preferred.

**Comment by mcmonkey4eva** [comment]
Please reply below if this remains as an issue, I will reopen the issue post.
