### ISSUE TITLE
angry wolf in sentinel with kill quest broken and spams console

### ISSUE THREAD

**Issue by ScuroK** [mcmonkey4eva/Sentinel#240]
when i used an angry wolf as sentinel i got a ton of errors.

here is the complete log of what i did:
https://www.dropbox.com/s/gt5pxadh0vial6h/latest.log?dl=0

**Comment by mcmonkey4eva** [comment]
Do you perhaps have some other plugin modifying the max health of the Sentinel NPC?

It appears to have been set on the entity to `8` as a max health value but that information was not ever seen by Sentinel.

**Comment by ScuroK** [comment]
i dont think i have any plugin i could imagine to influence this.
i do use sentinel together with Quests (see linked issue). i dont know if quests fo something on it or not.

**Comment by ScuroK** [comment]
![2018-03-30_20 03 04](https://user-images.githubusercontent.com/10480144/38148180-aa64413c-3455-11e8-98d4-5cbd26264d04.png)

**Comment by ScuroK** [comment]
with other sentinels rather than wolfs i dont have this problems.

**Comment by ScuroK** [comment]
what i can say is that the errors start to pop up after i safed the quest.

**Comment by mcmonkey4eva** [comment]
It's likely an error directly caused by another plugin misbehaving.

I have added some helper logic to the latest sentinel build (DEV-164+) on http://ci.citizensnpcs.co/job/Sentinel/
It will (attempt to) forcibly correct the situation if another plugin improperly alters the health of a Sentinel NPC, to avoid errors.

**Comment by ScuroK** [comment]
thx alot.
