### ISSUE TITLE
Wont drop drops or go teleport to path when stuck

### ISSUE THREAD

**Issue by Death1030** [mcmonkey4eva/Sentinel#247]
I'm working on a pirate ship raid for players on my server to participate in. so of course i have pirates above patrolling the deck of the ship. But once they fall into the water, they lose all sense and start spazzing out rather than teleporting back to the deck or climbing the ladder to the ship. Also i have them set to drop some items when they are killed, but no matter how many times I or anybody else slays them, they do not drop any items.

**Comment by mcmonkey4eva** [comment]
Teleport to path: That's a Citizens issue. Sentinel does not alter pathfinding / patrol routes / etc.

Drops: you might have a plugin or configuration blocking drops. If you can find it and fix it, that'd be ideal. Otherwise, you can enable the `workaround drops` option in the Sentinel config: https://github.com/mcmonkey4eva/Sentinel/blob/master/src/main/resources/config.yml#L49-L50
