### ISSUE TITLE
Sentinel attackrate should also be the time it takes for them to search for their old path

### ISSUE THREAD

**Issue by CorporalBruno** [mcmonkey4eva/Sentinel#34]
Sentinel attackrate should also be the time it takes for them to search for their old path.

For instance. If the sentinels attack rate is set to 110. It should only continue to target/chase its targets for that 110 ticks. If no targets are found by the end of the 110 ticks it should return to its path, if it does find possible targets it continues its chase to engage. This should end the circling motion.

**Comment by mcmonkey4eva** [comment]
I think the circling is two things:
First: Caused by citizens being a meanie and trying to force its own path the moment my custom path is done, before I restart it a few ticks later.
Second: Useful. It's like combat dodging. I can probably remove it using events but I think it's a pretty neat maneuver.
